version: '3'
services:
  db:
    image: postgis/postgis
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
    links:
    - db

  server:
    # env_file:
    image: test-server
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  pgdata:
    external: true
